# eksctl create cluster --managed=false --dry-run 
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nhance-dev1
  region: ap-south-1
  version: "1.31"
  tags:
    environment: development
availabilityZones:
- ap-south-1a
- ap-south-1b
- ap-south-1c

# 1) eksctl utils update-authentication-mode -f config.yaml 2> /dev/null 
accessConfig:
  authenticationMode: API_AND_CONFIG_MAP

# 3) eksctl utils update-cluster-logging --config-file config.yaml --approve           
cloudWatch:
  clusterLogging: {}
    # enableTypes: ["*"]
    # ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    # logRetentionInDays: 7

privateCluster:
  enabled: false
  skipEndpointCreation: false

iam:
  vpcResourceControllerPolicy: true
  # 4) eksctl utils associate-iam-oidc-provider -f config.yaml --approve
  withOIDC: true
  # https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html
  # withAddonPolicies:
  #   albIngress: false
  #   imageBuilder: true
  #   autoScaler: true
  #   externalDNS: true
  #   certManager: true
  #   appMesh: true
  #   appMeshPreview: true
  #   ebs: true
  #   fsx: true
  #   efs: true
  #   awsLoadBalancerController: true
  #   xRay: true
  #   cloudWatch: true

# 5) eksctl create/update addon -f config.yaml
addonsConfig:
  disableDefaultAddons: false
  autoApplyPodIdentityAssociations: true

# bear in mind that if either pod identity or IRSA configuration is explicitly set in the config file,
# or if the addon does not support pod identities,
# addonsConfig.autoApplyPodIdentityAssociations won't have any effect.

addons:
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: eks-pod-identity-agent
  version: latest

# - name: vpc-cni
#   version: latest
#   # useDefaultPodIdentityAssociations: true
#   tags:
#     team: eks
#   podIdentityAssociations:
#   - serviceAccountName: aws-node
#     namespace : kube-system
#     permissionPolicyARNs: ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]

- name: vpc-cni
  # all below properties are optional
  version: latest
  tags:
    team: eks
  # you can specify at most one of:
  attachPolicyARNs:
  # - arn:aws:iam::account:policy/AmazonEKS_CNI_Policy
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  # or
  # serviceAccountRoleARN: arn:aws:iam::account:role/AmazonEKSCNIAccess
  resolveConflicts: overwrite
  
  # or
  # attachPolicy:
  #   Statement:
  #   - Effect: Allow
  #     Action:
  #     - ec2:AssignPrivateIpAddresses
  #     - ec2:AttachNetworkInterface
  #     - ec2:CreateNetworkInterface
  #     - ec2:DeleteNetworkInterface
  #     - ec2:DescribeInstances
  #     - ec2:DescribeTags
  #     - ec2:DescribeNetworkInterfaces
  #     - ec2:DescribeInstanceTypes
  #     - ec2:DetachNetworkInterface
  #     - ec2:ModifyNetworkInterfaceAttribute
  #     - ec2:UnassignPrivateIpAddresses
  #     Resource: '*'

managedNodeGroups:
- name: ng-nhance-dev1
  amiFamily: AmazonLinux2
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
  disableIMDSv1: true
  disablePodIMDS: false
  volumeIOPS: 3000
  volumeSize: 30
  volumeThroughput: 125
  volumeType: gp3
  privateNetworking: false

  # instanceSelector: {}
  #   vCPUs: 2
  #   memory: 2GiB #
  #   cpuArchitecture: x86_64 # default value
  #   instanceTypes:
  #   - t3.medium

  # instanceTypes` defaults to [`m5.large`]
  # spot: true
  
  releaseVersion: ""
  
  ssh:
    allow: true
    # enableSsm: false
    # publicKeyPath: ""
    publicKeyName: "twin_bastion"
  securityGroups:
    withLocal: null #true in self-managed nodegroup
    withShared: null #true in self-managed nodegroup
  labels:
    alpha.eksctl.io/cluster-name: nhance-dev1
    alpha.eksctl.io/nodegroup-name: ng-nhance-dev1
  tags:
    alpha.eksctl.io/nodegroup-name: ng-nhance-dev1
    alpha.eksctl.io/nodegroup-type: managed
    
# highly-available-cluster
zonalShiftConfig:
  enabled: false

kubernetesNetworkConfig:
  ipFamily: IPv4
vpc:
  autoAllocateIPv6: false
  cidr: 10.30.0.0/16
  # eksctl utils update-cluster-vpc-config -f config.yaml --approve
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single # other options: HighlyAvailable, Disable, Single (default)

# eksctl delete cluster -f config.yaml --wait
