# refLink : https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

# Example configuration for the webserver at https://github.com/monopole/hello
# commonLabels:
#   app: hello

resources:
- ./jobs-ingress.yaml
- ./prom-grafana-ingress.yaml
- ./argocd-ingress.yaml
- ./tekton-ingress.yaml