---
# Git repositories configure Argo CD with (optional).
# This list is updated when configuring/removing repos from the UI/CLI
# Note: the last example in the list would use a repository credential template, configured under "argocd-repo-creds.yaml".
apiVersion: v1
kind: Secret
metadata:
  name: eks-manifest-nhance
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: eks-manifest-nhance
  project: nhance-dev
  url: https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/eks-manifest-nhance
  password: nE50HkH7DVOQfvX+Zxx7MKhJiq9ztUjElFbO6MBeFui6kbWFuvbu1mMI5Ws=
  username: interactionone-at-046874047165
  insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
  forceHttpBasicAuth: "true" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
