apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-jobs-deploy-svc-hpa
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  labels:
    name: dev-jobs-deploy-svc-hpa
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd # default
    argocd-image-updater.argoproj.io/image-list: |
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_adrianse:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_nhance:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_fidelity:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_bosch:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_ubl:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_brfr:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_nucleus:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_rmz:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_ccl:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_loop360:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_opentext:development,
      046874047165.dkr.ecr.ap-south-1.amazonaws.com/jobs_apar:development
    # argocd-image-updater.argoproj.io/image-list: api=registry.com/vendor/api:1.x,front=registry.com/vendor/front:1.x
    #argocd-image-updater.argoproj.io/update-strategy: semver # to apply for all the images
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    # argocd-image-updater.argoproj.io/api.update-strategy: semver
    # argocd-image-updater.argoproj.io/front.update-strategy: semver

spec:
  # project: default
  project: nhance-dev
  # Source of the application manifests
  source:
    repoURL: https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/eks-manifest-nhance   # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD
    path: dev-env/3_jobs_deploy_svc_hpa
    
    # # directory
    # directory:
    #   recurse: true
    #   # Exclude contains a glob pattern to match paths against that should be explicitly excluded from being used during
    #   # manifest generation. This takes precedence over the `include` field.
    #   # To match multiple patterns, wrap the patterns in {} and separate them with commas. For example: '{config.yaml,env-use2/*}'
      # exclude: 'kustomization.yaml'
      # exclude: 'config.yaml'
    #   # Include contains a glob pattern to match paths against that should be explicitly included during manifest
    #   # generation. If this field is set, only matching manifests will be included.
    #   # To match multiple patterns, wrap the patterns in {} and separate them with commas. For example: '{*.yml,*.yaml}'
      # include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    # automated: null

    # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
    #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    #   selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    #   allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration
    - ApplyOutOfSyncOnly=true # Only sync out-of-sync resources, rather than applying every object in the application

    # The retry feature is available since v1.7
    retry:
      limit: 2 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m0s # the maximum amount of time allowed for the backoff strategy

  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 3
  # revisionHistoryLimit: 10
