# refLink : https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

# Example configuration for the webserver at https://github.com/monopole/hello
# commonLabels:
#   app: hello

resources:
- ./1-project.yaml
- ./2-argocd-ecr-repositories.yaml
- ./3-jobs-deploy-svc-hpa-app.yaml
# - argocd-image-updater-cm.yaml
# - argocd-image-updater-secret.yaml
# - argocd-image-updater-ssh-config.yaml